const result = [
  {
    imageUrl:
      'http://p1.music.126.net/NoKR6O5I6vI2WhpdTZbunQ==/109951166949297800.jpg',
    targetId: 138676183,
    adid: null,
    targetType: 10,
    titleColor: 'red',
    typeTitle: '新碟首发',
    url: null,
    exclusive: false,
    monitorImpress: null,
    monitorClick: null,
    monitorType: null,
    monitorImpressList: null,
    monitorClickList: null,
    monitorBlackList: null,
    extMonitor: null,
    extMonitorInfo: null,
    adSource: null,
    adLocation: null,
    adDispatchJson: null,
    encodeId: '138676183',
    program: null,
    event: null,
    video: null,
    song: null,
    scm: '1.music-homepage.homepage_banner_force.banner.4175968.-1143545511.null',
  },
  {
    imageUrl:
      'http://p1.music.126.net/x57nohLe5BQu0rTcGqxvaQ==/109951166948707399.jpg',
    targetId: 134091274,
    adid: null,
    targetType: 10,
    titleColor: 'red',
    typeTitle: '新碟首发',
    url: null,
    exclusive: false,
    monitorImpress: null,
    monitorClick: null,
    monitorType: null,
    monitorImpressList: null,
    monitorClickList: null,
    monitorBlackList: null,
    extMonitor: null,
    extMonitorInfo: null,
    adSource: null,
    adLocation: null,
    adDispatchJson: null,
    encodeId: '134091274',
    program: null,
    event: null,
    video: null,
    song: null,
    scm: '1.music-homepage.homepage_banner_force.banner.4184983.-1143659833.null',
  },
  {
    imageUrl:
      'http://p1.music.126.net/7aSebUP3-k-M1lB1s6AqSg==/109951166950127895.jpg',
    targetId: 0,
    adid: null,
    targetType: 3000,
    titleColor: 'blue',
    typeTitle: '活动',
    url: 'https://music.163.com/m/at/61e65b2199ee2e9180c3759d',
    exclusive: false,
    monitorImpress: null,
    monitorClick: null,
    monitorType: null,
    monitorImpressList: null,
    monitorClickList: null,
    monitorBlackList: null,
    extMonitor: null,
    extMonitorInfo: null,
    adSource: null,
    adLocation: null,
    adDispatchJson: null,
    encodeId: '0',
    program: null,
    event: null,
    video: null,
    song: null,
    scm: '1.music-homepage.homepage_banner_force.banner.4166978.-1143695393.null',
  },
  {
    imageUrl:
      'http://p1.music.126.net/j8xmL7Evl8z23hklabcEVg==/109951166948731612.jpg',
    targetId: 1911249448,
    adid: null,
    targetType: 1,
    titleColor: 'red',
    typeTitle: '新歌首发',
    url: null,
    exclusive: false,
    monitorImpress: null,
    monitorClick: null,
    monitorType: null,
    monitorImpressList: null,
    monitorClickList: null,
    monitorBlackList: null,
    extMonitor: null,
    extMonitorInfo: null,
    adSource: null,
    adLocation: null,
    adDispatchJson: null,
    encodeId: '1911249448',
    program: null,
    event: null,
    video: null,
    song: null,
    scm: '1.music-homepage.homepage_banner_force.banner.4184984.-1143667557.null',
  },
  {
    imageUrl:
      'http://p1.music.126.net/RJDqMDE1JnEGrZ8wszzNiQ==/109951166948744529.jpg',
    targetId: 98966424,
    adid: null,
    targetType: 10,
    titleColor: 'red',
    typeTitle: '热门推荐',
    url: null,
    exclusive: false,
    monitorImpress: null,
    monitorClick: null,
    monitorType: null,
    monitorImpressList: null,
    monitorClickList: null,
    monitorBlackList: null,
    extMonitor: null,
    extMonitorInfo: null,
    adSource: null,
    adLocation: null,
    adDispatchJson: null,
    encodeId: '98966424',
    program: null,
    event: null,
    video: null,
    song: null,
    scm: '1.music-homepage.homepage_banner_force.banner.4184985.-1143779180.null',
  },
  {
    imageUrl:
      'http://p1.music.126.net/_7ZUs0UlS9DGTTHCdlrS3w==/109951166949311338.jpg',
    targetId: 1912955885,
    adid: null,
    targetType: 1,
    titleColor: 'red',
    typeTitle: '新歌首发',
    url: null,
    exclusive: false,
    monitorImpress: null,
    monitorClick: null,
    monitorType: null,
    monitorImpressList: null,
    monitorClickList: null,
    monitorBlackList: null,
    extMonitor: null,
    extMonitorInfo: null,
    adSource: null,
    adLocation: null,
    adDispatchJson: null,
    encodeId: '1912955885',
    program: null,
    event: null,
    video: null,
    song: null,
    scm: '1.music-homepage.homepage_banner_force.banner.4184986.-1143662875.null',
  },
  {
    imageUrl:
      'http://p1.music.126.net/jGbu6jx4GrqDzOLSLA8Cqw==/109951166949317362.jpg',
    targetId: 1912858924,
    adid: null,
    targetType: 1,
    titleColor: 'red',
    typeTitle: '新歌首发',
    url: null,
    exclusive: false,
    monitorImpress: null,
    monitorClick: null,
    monitorType: null,
    monitorImpressList: null,
    monitorClickList: null,
    monitorBlackList: null,
    extMonitor: null,
    extMonitorInfo: null,
    adSource: null,
    adLocation: null,
    adDispatchJson: null,
    encodeId: '1912858924',
    program: null,
    event: null,
    video: null,
    song: null,
    scm: '1.music-homepage.homepage_banner_force.banner.4177970.-1143575513.null',
  },
  {
    imageUrl:
      'http://p1.music.126.net/51N_1AsOmfOU2cbLwJlFpw==/109951166948768284.jpg',
    targetId: 1912593420,
    adid: null,
    targetType: 1,
    titleColor: 'red',
    typeTitle: '新歌首发',
    url: null,
    exclusive: false,
    monitorImpress: null,
    monitorClick: null,
    monitorType: null,
    monitorImpressList: null,
    monitorClickList: null,
    monitorBlackList: null,
    extMonitor: null,
    extMonitorInfo: null,
    adSource: null,
    adLocation: null,
    adDispatchJson: null,
    encodeId: '1912593420',
    program: null,
    event: null,
    video: null,
    song: null,
    scm: '1.music-homepage.homepage_banner_force.banner.4169973.-1143546589.null',
  },
  {
    imageUrl:
      'http://p1.music.126.net/oR_GXbWyQ3M-GV8MmnpIhg==/109951166949332760.jpg',
    targetId: 1912666127,
    adid: null,
    targetType: 1,
    titleColor: 'red',
    typeTitle: '新歌首发',
    url: null,
    exclusive: false,
    monitorImpress: null,
    monitorClick: null,
    monitorType: null,
    monitorImpressList: null,
    monitorClickList: null,
    monitorBlackList: null,
    extMonitor: null,
    extMonitorInfo: null,
    adSource: null,
    adLocation: null,
    adDispatchJson: null,
    encodeId: '1912666127',
    program: null,
    event: null,
    video: null,
    song: null,
    scm: '1.music-homepage.homepage_banner_force.banner.4200973.-1143573371.null',
  },
  {
    imageUrl:
      'http://p1.music.126.net/pxPos_B1xuVhXPC-xp4fLw==/109951166948916007.jpg',
    targetId: 1912960614,
    adid: null,
    targetType: 1,
    titleColor: 'red',
    typeTitle: '新歌首发',
    url: null,
    exclusive: false,
    monitorImpress: null,
    monitorClick: null,
    monitorType: null,
    monitorImpressList: null,
    monitorClickList: null,
    monitorBlackList: null,
    extMonitor: null,
    extMonitorInfo: null,
    adSource: null,
    adLocation: null,
    adDispatchJson: null,
    encodeId: '1912960614',
    program: null,
    event: null,
    video: null,
    song: null,
    scm: '1.music-homepage.homepage_banner_force.banner.4170984.-1143784795.null',
  },
]
module.exports = result
